"use client";

import { Cloud, Sparkles } from "lucide-react";
import { useState } from "react";

export default function CloudflareImageTest() {
  const [prompt, setPrompt] = useState("A cinematic realistic scene inside a futuristic AI office in Jakarta, a young software engineer working at a desk, warm practical lighting, detailed environment, cinematic composition, 16:9.");
  const [loading, setLoading] = useState(false);
  const [image, setImage] = useState("");
  const [result, setResult] = useState("");

  const test = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setImage("");
    setResult("Testing Cloudflare Workers AI image generation…");

    try {
      const response = await fetch("/api/cloudflare/image-test", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt.trim() }),
      });
      const data = await response.json();

      if (!response.ok || !data.ok) {
        setResult(`IMAGE TEST FAILED · ${data.code ?? "unknown"} · ${data.error ?? "request failed"}`);
        return;
      }

      setImage(`data:${data.mimeType ?? "image/png"};base64,${data.imageBase64}`);
      setResult(`IMAGE TEST SUCCESS · ${data.model} · Cloudflare Workers AI returned an image.`);
    } catch {
      setResult("IMAGE TEST FAILED · Could not reach the local Cloudflare image endpoint.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="card">
      <div className="title"><Cloud size={14}/> CLOUDFLARE IMAGE PROVIDER TEST</div>
      <div className="muted" style={{lineHeight:1.6,margin:"8px 0 12px"}}>
        Uses Cloudflare Workers AI server-side. The Cloudflare token stays in .env.local.
        Default model: SDXL-Lightning.
      </div>
      <div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}>
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          rows={3}
          disabled={loading}
          style={{width:"100%",resize:"vertical",padding:10,borderRadius:10,border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.03)",color:"inherit"}}
        />
        <button className="ctrl green compact" style={{alignSelf:"start",height:"fit-content"}} disabled={loading} onClick={test}>
          <Sparkles size={14}/>{loading ? "Testing…" : "Test Cloudflare Image"}
        </button>
      </div>
      {result && <div className="notice" style={{marginTop:10,whiteSpace:"pre-wrap"}}>{result}</div>}
      {image && <div style={{marginTop:10,borderRadius:12,overflow:"hidden",background:"#10141b"}}><img src={image} alt="Generated by Cloudflare Workers AI" style={{display:"block",width:"100%",height:"auto"}} /></div>}
    </div>
  );
}
