"use client";

import { Sparkles } from "lucide-react";
import { useState } from "react";

export default function GeminiImageTest() {
  const [prompt, setPrompt] = useState("Generate a cinematic, realistic deep-ocean submarine scene with dramatic volumetric lighting, detailed water particles, and a wide 16:9 composition.");
  const [loading, setLoading] = useState(false);
  const [image, setImage] = useState("");
  const [result, setResult] = useState("");

  const test = async () => {
    if (!prompt.trim()) return;
    setLoading(true);
    setImage("");
    setResult("Testing Gemini image generation…");
    try {
      const response = await fetch("/api/gemini/image-test", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: prompt.trim() }),
      });
      const data = await response.json();

      if (!response.ok || !data.ok) {
        setResult(`GEMINI IMAGE TEST FAILED · ${data.code ?? "unknown"} · ${data.error ?? "request failed"}`);
        return;
      }

      setImage(`data:${data.mimeType ?? "image/png"};base64,${data.imageBase64}`);
      setResult(`GEMINI IMAGE TEST SUCCESS · ${data.model} · Image returned from Gemini API.`);
    } catch {
      setResult("GEMINI IMAGE TEST FAILED · Could not reach the local Gemini endpoint.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="card">
      <div className="title"><Sparkles size={14}/> GEMINI IMAGE PROVIDER TEST</div>
      <div className="muted" style={{lineHeight:1.6,margin:"8px 0 12px"}}>
        Backend-only test. The Gemini API key stays on the server in GEMINI_API_KEY.
      </div>
      <div style={{display:"grid",gridTemplateColumns:"1fr auto",gap:8}}>
        <textarea
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          rows={3}
          disabled={loading}
          style={{width:"100%",resize:"vertical",padding:10,borderRadius:10,border:"1px solid rgba(255,255,255,.12)",background:"rgba(255,255,255,.03)",color:"inherit"}}
        />
        <button className="ctrl green compact" style={{alignSelf:"start",height:"fit-content"}} disabled={loading} onClick={test}>
          <Sparkles size={14}/>{loading ? "Testing…" : "Test Gemini Image"}
        </button>
      </div>
      {result && <div className="notice" style={{marginTop:10,whiteSpace:"pre-wrap"}}>{result}</div>}
      {image && <div style={{marginTop:10,borderRadius:12,overflow:"hidden",background:"#10141b"}}><img src={image} alt="Generated by Gemini" style={{display:"block",width:"100%",height:"auto"}} /></div>}
    </div>
  );
}
