export const GEMI_VISUAL_PROFILE = [
  "GEMI VISUAL PROFILE — 3D CHARACTER & SCENE ARTIST",
  "Primary medium: cute polished 3D animation for vertical social video.",
  "Overall look: adorable, playful, charming, cinematic, premium animated-film quality.",
  "Character design: chibi/toy-like proportions, slightly oversized heads, rounded cheeks, large expressive eyes, simplified readable shapes, soft silhouettes, appealing facial expressions.",
  "Materials: smooth polished 3D surfaces, soft fabric, clean toy-like details where appropriate, subtle skin shading, no gritty texture.",
  "Color direction: cheerful controlled color palette, warm highlights, gentle contrast, saturated accents without neon overload.",
  "Lighting: soft cinematic key light, gentle fill, soft rim light, subtle volumetric light, pleasant depth of field.",
  "World design: cozy miniature environments, charming props, rounded furniture, visually rich but uncluttered backgrounds.",
  "Acting: dynamic animation keyframes, exaggerated but natural poses, clear weight shifts, bent knees/elbows, asymmetrical silhouettes, readable hand gestures, strong facial emotion, visible character relationships.",
  "Motion-first staging: every frame should capture a moment DURING an action, not before or after it. Use movement verbs such as reaching, turning, running, stopping, grabbing, pointing, hugging, recoiling, leaning, stepping, opening, closing, or handing an object.",
  "Expression-first posing: face, torso, arms, and gaze must communicate the same emotional beat. Avoid mannequin-like neutral posture.",
  "Composition energy: prefer diagonal lines, layered foreground/midground, varied character heights, and clear subject separation. Avoid perfectly symmetrical front-facing poses.",

  "Framing: 9:16 vertical composition designed for a phone screen; keep faces and important props large enough to read immediately.",
  "Continuity lock: preserve face shape, eye shape, hair/head features, body proportions, signature clothing, footwear, accessories, colors, props, and overall rendering style across every scene.",
  "Scene identity: each image must feel like the next shot from the same animated movie, with consistent world scale and art direction.",
  "Priority: character readability and emotional acting first, then environment detail.",
  "Default shot behavior: treat the image as an animation keyframe from a moving scene. Freeze an expressive instant with visible action, interaction, or reaction.",

].join("\n");

export const GEMI_NEGATIVE_PROFILE = [
  "photorealistic",
  "live-action",
  "realistic human proportions",
  "gritty realism",
  "dark horror",
  "anime",
  "manga",
  "comic book",
  "graphic novel",
  "2D illustration",
  "flat vector art",
  "sketch",
  "watercolor",
  "concept art",
  "poster",
  "character turnaround sheet",
  "text overlay",
  "captions",
  "subtitles",
  "logos",
  "UI",
  "extra characters",
  "random costume changes",
  "different face",
  "different hairstyle",
  "static portrait",
  "passport photo",
  "studio pose",
  "standing straight",
  "arms at sides",
  "stiff mannequin pose",
  "symmetrical front-facing pose",
  "emotionless face",
  "frozen neutral pose",
  "empty hands when an action is specified",
].join(", ");
